import Head from "next/head";
import React from "react";
import { HomeContainer } from "../feature/Home/containers/Home";
import { moviesAPI } from "../../../topic8/movieapp/src/api/home";
import Layout  from "../shared/components/Layout"


const HomePage = (props) => {
  return (
      <Layout>
      <Head>
        <title>Home App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HomeContainer data={props.movies} />
      </Layout>
  );
};

export default HomePage;

export const getServerSideProps = async (context) => {
  const response = await moviesAPI;

  if (!response) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      movies: response?.data?.Search,
    },
  };
};
