import Head from "next/head";
import React, { useEffect } from "react";
import { HomeContainer } from "../feature/Home/containers/Home";
import { moviesAPI } from "../../../topic8/movieapp/src/api/home";
import Layout  from "../shared/components/Layout"
import axios from "axios"

const HomePage = (props) => {

  useEffect(()=>{
    getActors()
  },[])


  const getActors = ()=>{

    axios("http://localhost:3000/api/actors").then(data=>{
      console.log("actors",data);
    })
  }



  return (
      <Layout>
      <Head>
        <title>Home Apaap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HomeContainer data={props.movies} />
      </Layout>
  );
};

export default HomePage;

export const getServerSideProps = async (context) => {
  const response = await moviesAPI;

  if (!response) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      movies: response?.data?.Search,
    },
  };
};
