

export const FILL_MOVIES = "FILL_MOVIES"
export const SET_COUNT = "SET_COUNT"
export const SHOW_PANEL = "SHOW_PANEL"
export const CHANGE_USER_ACCESS = "CHANGE_USER_ACCESS"
export const CURRENT_MOVIE = "CURRENT_MOVIE"
